export { default as Dashboard } from "./Dashboard";
export {default as Login} from "./Login";
export {default as Profile} from "./Profile";
export {default as User} from "./User";
export {default as Sign_up} from "./Sign_up";
export {default as Showprofile} from "./showprofile";
export {default as Office} from "./office";
export {default as Service} from "./serivce";
export {default as ShowOffice} from './showoffice';
export {default as Order} from './order';
export {default as ShowOrder} from './showorder';
export {default as Archive} from './Archive';
export {default as Chats} from './chats';
//export {default as Chackemail} from './chackemail';
//export {default as NotFound} from "./NotFound";
export { default as TEST } from "./test";