export { default as Dashboard } from "./Dashboard";
export {default as Login} from "./Login";
export {default as Profile} from "./Profile";
export {default as User} from "./User";
export {default as Sign_up} from "./Sign_up";
export {default as Showprofile} from "./showprofile";
export {default as Office} from "./Office/office";
export {default as Service} from "./Services/serivce";
export {default as ShowOffice} from './Office/showoffice';
export {default as Order} from './Order/order';
export {default as ShowOrder} from './Order/showorder';
export {default as Trackorder} from './Order/trackorder';
export {default as Archive} from './Archive';
export {default as Chats} from './Chats/chats';
export {default as ShowEmployee} from './Employee/showEmployee';
export {default as City} from './City/showCity';
//export {default as Chackemail} from './chackemail';
//export {default as NotFound} from "./NotFound";
export { default as TEST } from "./test";
//export {default as Chackemail} from './chackemail';