export { default as Dashboard } from "./Dashboard";
export {default as Login} from "./Login";
export {default as Profile} from "./Profile";
export {default as User} from "./User";
export {default as Modele} from "./Modele";
export {default as Sign_up} from "./Sign_up";
export {default as NotFound} from "./NotFound";
export {default as Forgottenpass} from "./forgottenpass";
export {default as Chackemail} from "./chackemail";
export {default as Verifyemail} from "./verify-email";
export {default as Resetpassword} from "./resetpassword";
export {default as Showprofile} from "./showprofile";
//export { default as Dashboard } from "./Dashboard";